roboflow:
  api_key: "W0tuxZXjcNxtJkv6j9ew"  # Can override with --api-key
  workspace: "datasets-7vdpa"
  project: "visdrone-zzrsu"

dataset:
  name: "visdrone-zzrsu-5"
  version: 5
  overwrite: False

model:
  path: "Yolo11m.pt"

validation:
  batch_size: 16
  imgsz: 640
  conf_threshold: 0.001
  iou_threshold: 0.6

hardware:
  device: "auto"  # cpu, cuda, or auto-detect